// 30 NJ Shore beaches, north to south
// Badge prices verified against Patch 2026 Jersey Shore Beach Badge Guide (Apr 2026)
// Coordinates are approximate centers; weather/tide APIs snap to nearest grid anyway
// Last verified: May 2026

const BEACHES = [
  { id: 'sandy-hook',       name: 'Sandy Hook',                town: 'Highlands',       county: 'Monmouth', lat: 40.4262, lon: -73.9882, badgePrice: 0,  parkingNotes: 'Free badge (NPS), parking $20/day weekday & weekend, $100/season',                    vibe: 'wild' },
  { id: 'sea-bright',       name: 'Sea Bright Public Beach',   town: 'Sea Bright',      county: 'Monmouth', lat: 40.3618, lon: -73.9740, badgePrice: 10, parkingNotes: 'Pay2Park app, municipal lot fills fast',                                            vibe: 'classic' },
  { id: 'monmouth-beach',   name: 'Monmouth Beach',            town: 'Monmouth Beach',  county: 'Monmouth', lat: 40.3340, lon: -73.9779, badgePrice: 15, parkingNotes: 'Season parking $70 (not guaranteed), limited spots',                              vibe: 'quiet' },
  { id: 'long-branch',      name: 'Pier Village Beach',        town: 'Long Branch',     county: 'Monmouth', lat: 40.3009, lon: -73.9857, badgePrice: 9,  parkingNotes: '$10/day in municipal lots, $6 weekday daily badge, $9 weekend',                  vibe: 'lively' },
  { id: 'deal',             name: 'Deal Beach',                town: 'Deal',            county: 'Monmouth', lat: 40.2532, lon: -73.9943, badgePrice: 15, parkingNotes: 'Residential streets only, $12 weekday badge / $15 weekend',                       vibe: 'quiet' },
  { id: 'asbury-park',      name: 'Asbury Park Beach',         town: 'Asbury Park',     county: 'Monmouth', lat: 40.2204, lon: -74.0021, badgePrice: 10, parkingNotes: 'ParkMobile metered, $7 weekday badge / $10 weekend',                              vibe: 'lively' },
  { id: 'ocean-grove',      name: 'Ocean Grove Beach',         town: 'Ocean Grove',     county: 'Monmouth', lat: 40.2123, lon: -74.0048, badgePrice: 13, parkingNotes: 'Free street parking, walk-in beach, closed Sun mornings',                         vibe: 'classic' },
  { id: 'bradley-beach',    name: 'Bradley Beach',             town: 'Bradley Beach',   county: 'Monmouth', lat: 40.2023, lon: -74.0124, badgePrice: 13, parkingNotes: 'Metered street parking, season $90 adult / $35 senior',                           vibe: 'family' },
  { id: 'avon',             name: 'Avon-by-the-Sea Beach',     town: 'Avon',            county: 'Monmouth', lat: 40.1907, lon: -74.0162, badgePrice: 13, parkingNotes: 'On-street only, diagonal/parallel by ordinance',                                  vibe: 'family' },
  { id: 'belmar',           name: 'Belmar Beach',              town: 'Belmar',          county: 'Monmouth', lat: 40.1788, lon: -74.0179, badgePrice: 12, parkingNotes: 'ParkMobile beachfront paid, season badge $80 adult',                              vibe: 'lively' },
  { id: 'spring-lake',      name: 'Spring Lake Beach',         town: 'Spring Lake',     county: 'Monmouth', lat: 40.1535, lon: -74.0276, badgePrice: 11, parkingNotes: 'Residential walk-in, season $110 adult / $80 senior',                            vibe: 'classic' },
  { id: 'manasquan',        name: 'Manasquan Beach',           town: 'Manasquan',       county: 'Monmouth', lat: 40.1198, lon: -74.0376, badgePrice: 12, parkingNotes: 'Metered lots fill early, season $90 adult',                                       vibe: 'surf' },
  { id: 'point-pleasant',   name: 'Point Pleasant Beach',      town: 'Point Pleasant',  county: 'Ocean',    lat: 40.0901, lon: -74.0381, badgePrice: 18, parkingNotes: "Jenkinson's lot $20/day, multiple beaches: Jenkinson's, Maryland Ave, Bradshaw's", vibe: 'family' },
  { id: 'bay-head',         name: 'Bay Head Beach',            town: 'Bay Head',        county: 'Ocean',    lat: 40.0712, lon: -74.0445, badgePrice: 14, parkingNotes: 'Residential parking only, badges req mid-June, cash only',                       vibe: 'quiet' },
  { id: 'mantoloking',      name: 'Mantoloking Beach',         town: 'Mantoloking',     county: 'Ocean',    lat: 40.0395, lon: -74.0509, badgePrice: 15, parkingNotes: 'Very limited residential, credit/check only at sales shed',                      vibe: 'quiet' },
  { id: 'lavallette',       name: 'Lavallette Beach',          town: 'Lavallette',      county: 'Ocean',    lat: 39.9712, lon: -74.0698, badgePrice: 13, parkingNotes: 'Free street parking, bayfront lot $15/season',                                   vibe: 'family' },
  { id: 'seaside-heights',  name: 'Seaside Heights Beach',     town: 'Seaside Heights', county: 'Ocean',    lat: 39.9412, lon: -74.0735, badgePrice: 13, parkingNotes: 'Boardwalk lots $15-25/day, season badge $75',                                   vibe: 'lively' },
  { id: 'seaside-park',     name: 'Seaside Park Beach',        town: 'Seaside Park',    county: 'Ocean',    lat: 39.9226, lon: -74.0791, badgePrice: 13, parkingNotes: 'Metered street parking, season badge $65-70',                                   vibe: 'family' },
  { id: 'island-beach',     name: 'Island Beach State Park',   town: 'Berkeley',        county: 'Ocean',    lat: 39.8079, lon: -74.0871, badgePrice: 0,  parkingNotes: 'Park entry $6 NJ weekday / $10 weekend, $12 / $20 non-resident',                 vibe: 'wild' },
  { id: 'barnegat-light',   name: 'Barnegat Light Beach',      town: 'Barnegat Light',  county: 'Ocean',    lat: 39.7615, lon: -74.1062, badgePrice: 10, parkingNotes: 'Lighthouse lot, season badge $40 (early) / $50',                                vibe: 'quiet' },
  { id: 'harvey-cedars',    name: 'Harvey Cedars Beach',       town: 'Harvey Cedars',   county: 'Ocean',    lat: 39.7003, lon: -74.1399, badgePrice: 7,  parkingNotes: 'Residential streets, season $40 (early), cash/check only',                      vibe: 'quiet' },
  { id: 'surf-city',        name: 'Surf City Beach',           town: 'Surf City',       county: 'Ocean',    lat: 39.6612, lon: -74.1671, badgePrice: 11, parkingNotes: 'Free street parking, season $45 (early) / $55',                                 vibe: 'family' },
  { id: 'ship-bottom',      name: 'Ship Bottom Beach',         town: 'Ship Bottom',     county: 'Ocean',    lat: 39.6418, lon: -74.1800, badgePrice: 10, parkingNotes: 'Free street parking, daily badge prices TBA',                                   vibe: 'family' },
  { id: 'beach-haven',      name: 'Beach Haven',               town: 'Beach Haven',     county: 'Ocean',    lat: 39.5612, lon: -74.2418, badgePrice: 10, parkingNotes: 'Metered street parking, season $40 (early) / $50',                              vibe: 'family' },
  { id: 'atlantic-city',    name: 'Atlantic City Beach',       town: 'Atlantic City',   county: 'Atlantic', lat: 39.3548, lon: -74.4324, badgePrice: 0,  parkingNotes: 'Free beach access, casino garages vary $10-30/day',                            vibe: 'lively' },
  { id: 'ventnor',          name: 'Ventnor Beach',             town: 'Ventnor City',    county: 'Atlantic', lat: 39.3401, lon: -74.4724, badgePrice: 10, parkingNotes: 'Free street parking, season $10 (early) / $20',                                 vibe: 'classic' },
  { id: 'ocean-city',       name: 'Ocean City Beach',          town: 'Ocean City',      county: 'Cape May', lat: 39.2776, lon: -74.5746, badgePrice: 10, parkingNotes: 'Metered street parking, season tag $30 (early) / $35',                          vibe: 'family' },
  { id: 'sea-isle-city',    name: 'Sea Isle City Beach',       town: 'Sea Isle City',   county: 'Cape May', lat: 39.1537, lon: -74.6921, badgePrice: 10, parkingNotes: 'Free street parking, Wednesdays free beach days',                               vibe: 'family' },
  { id: 'avalon',           name: 'Avalon Beach',              town: 'Avalon',          county: 'Cape May', lat: 39.1018, lon: -74.7187, badgePrice: 10, parkingNotes: 'Free street parking, reciprocal w/ Stone Harbor, season $37-42',                vibe: 'classic' },
  { id: 'cape-may',         name: 'Cape May Beach',            town: 'Cape May',        county: 'Cape May', lat: 38.9351, lon: -74.9060, badgePrice: 10, parkingNotes: 'Metered street parking fills fast, season $30-40, cash/check only',             vibe: 'classic' }
];

module.exports = BEACHES;